name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: 
    #     node-version: [ 20.x ]
    steps:
      # node-version: ${{ matrix.node-version }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # # steps: 
      # - uses: actions/checkout@v2
      # - name: Staring Node.js ${{ matrix.node-version }}
      # uses: actions/stup-node@v1
      # with:
      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v1.4.3
      #   with:
      #     node-version: [ 20.x ]
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit


